### ISSUE TITLE
how to use twig sandbox bundle?

### ISSUE THREAD

**Issue by wikingwei** [intaro/twig-sandbox-bundle#1]
Hi,

as described in readme file about how to use it, $twig = $this->get('intaro.twig_sandbox.builder')->getSandboxEnvironment();

Here, what is $this? I still don't know how to use it.

**Comment by muxx** [comment]
This example is for using in controller where services are available with help `$this->get()` method.

**Comment by wikingwei** [comment]
sorry, but I still don't know what controller or services, maybe they are part of your project.
could you tell me how to construct an EnvironmentBuilder object, so that I can call its getSandboxEnvironment()?
I can see the constructor of EnvironmentBuilder  needs an argument LoaderInterface $loader.
How to pass a valid $loader?

Thanks.

**Comment by muxx** [comment]
This bundle is for using in Symfony Framework. Loader, controller, services are terms of Symfony (http://symfony.com)

**Comment by wikingwei** [comment]
Thanks a lot.
