### ISSUE TITLE
It seems to stop globals from using.

### ISSUE THREAD

**Issue by kleand** [intaro/twig-sandbox-bundle#5]
At some point I include global in the $twig instance like this:
   $finderService = $this->container->get('finder_service');
   $twig->addGlobal('finder', $finderService );

When I include 
{{ finder.findOne('arg1', 'arg2', 'arg3') }}
it validates but when rendering generates error:  Calling "findone" method on a \"...EntityFinder\" object is not allowed in \"__string_template__0edef266c68e7d81a0718ac749a20f41c39c7e65251c3df9aa0e0c970f9166b9\" at line 1.

Also even if I include dump function under intaro.twig_sandbox.policy_functions it never allows me to use it when validating.

**Comment by muxx** [comment]
The bundle allows to call methods with annotation `@Sandbox`. You should add this annotation for `findOne` if you want to use it in twig sandbox.

**Comment by muxx** [comment]
Example of usage is here https://github.com/intaro/twig-sandbox-bundle#usage

**Comment by kleand** [comment]
Are you sure since the class is not an entity, is just a service
Even when I add the annotation it is still the same error

**Comment by muxx** [comment]
Yes, you right. If you want you can fork bundle and change this code https://github.com/intaro/twig-sandbox-bundle/blob/master/Builder/EnvironmentBuilder.php#L146 and parse not only `Entity` folder but whole bundle.

**Comment by kleand** [comment]
I don't think you solve it that way, as I am talking abound global so it will be accessed finder.findeOne where you through annotation will still be registering it as EntityFinder => array('findOne'), the best way would be to add 'intaro.twig_sandbox.policy_methods' where you merge with your annoation methods

**Comment by muxx** [comment]
Do you suggest allow to call any method of global vars? I not sure that it is sandbox-way.

**Comment by kleand** [comment]
I just made  a test and everything seems to be working fine:

        $twig = $this->container->get('intaro.twig_sandbox.builder')->getSandboxEnvironment([
            'strict_variables' => false,
            'cache' => false
        ]);

        $entityFinder = $this->container->get('entity_finder');
        $twig->addGlobal('finder', $entityFinder);

        $tags = ['if', 'for', 'set'];
        $filters = ['abs', 'batch', 'capitalize', 'convert_encoding', 'date', 'date_modify', 'default', 'escape', 'first', 'format',
            'join', 'json_encode', 'keys', 'last', 'length', 'lower', 'merge', 'nl2br', 'number_format', 'raw', 'replace',
            'reverse', 'round', 'slice', 'sort', 'split', 'striptags', 'title', 'trim', 'upper', 'url_encode'
        ];
        $methods = [
            EntityFinder::class => ['findOne']
        ];
        $properties = [];
        $functions = ['date', 'max', 'min', 'random', 'dump'];

        $policy = new \Twig_Sandbox_SecurityPolicy($tags, $filters, $methods, $properties, $functions);
        /**@var \Twig_Extension_Sandbox $sandbox*/
        /**@var \Twig\Sandbox\SecurityPolicyInterface*/
        $sandbox = $twig->getExtension('sandbox');
        $sandbox->setSecurityPolicy($policy);

Now I can access my method in template as: {% set someone=  finder.findOne('lead', 'email', 'test@email.com') %}

If I was able to set methods through key: 'intaro.twig_sandbox.policy_methods' in parameters it would not be necessary to override Twig_Sandbox_SecurityPolicy
